# Generated by Django 3.1.5 on 2021-01-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='题目')),
                ('category', models.CharField(choices=[('非技术', 'no-tec'), ('技术', 'tec')], max_length=20, verbose_name='分类')),
                ('limit', models.CharField(choices=[('公开的', 'public'), ('私有的', 'private')], max_length=10, verbose_name='权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改事件')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('introduce', models.CharField(max_length=90, verbose_name='博客内容介绍')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
